print("WELCOME TO HOSTEL MESS MANAGEMENT SYSTEM")
n="yes" 
while n!="no":
    print("Choose your hostel") 
    print("1. Kalpana Chawla") 
    print("2. Senbagam") 
    print("3. ESQ block") 
    print("4. Meenakshi") 
    n1=int(input("enter your choice 1,2,3 or 4:")) 
    if n1==1:
        print("You have chosen Kalpana Chawla")
        print("Select day:") 
        print("1. Monday") 
        print("2. Tuesday") 
        print("3. Wednesday") 
        print("4. Thursday") 
        print("5. Friday") 
        print("6.Saturday") 
        print("7. Sunday") 
        n2=int(input("enter your choice 1,2,3,4,5,6 or 7:"))
        if n2==1:
            print("You have chosen Monday") 
            print("Food menu is:") 
            print("1.breakfast= bread and jam")  
            print("2. lunch= rajma, rice and butter milk") 
            print("3. dinner= chicken gravy, paneer and roti") 
            n3=int(input("Choose your meal number:"))
            if n3==1:
                print("You have chosen Breakfast") 
                fc=int(input("enter amount of food consumed:")) 
                print("almost 20% of food from breakfast is wasted") 
                print("Amount of food wasted is",0.2*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==2:
                print("You have chosen Lunch") 
                fc=int(input("enter amount of food consumed:"))
                print("almost  30% of luch is wasted") 
                print("Amount of food wasted is",0.3*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==3:
                print("You have chosen Dinner")
                fc=int(input("enter amount of food consumed:"))
                print("almost 40% of dinneer is wasted") 
                print("Amount of food wasted is",0.4*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
        elif n2==2:
            print("You have chosen Tuesday") 
            print("Food menu is:") 
            print("1.breakfast= bread and jam")  
            print("2. lunch= rajma, rice and butter milk") 
            print("3. dinner= chicken gravy, paneer and roti") 
            n3=int(input("Choose your meal number:"))
            if n3==1:
                print("You have chosen Breakfast") 
                fc=int(input("enter amount of food consumed:")) 
                print("almost 20% of food from breakfast is wasted") 
                print("Amount of food wasted is",0.2*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==2:
                print("You have chosen Lunch") 
                fc=int(input("enter amount of food consumed:"))
                print("almost  30% of luch is wasted") 
                print("Amount of food wasted is",0.3*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==3:
                print("You have chosen Dinner")
                fc=int(input("enter amount of food consumed:"))
                print("almost 40% of dinneer is wasted") 
                print("Amount of food wasted is",0.4*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
        elif n2==3:
            print("You have chosen Wednesday") 
            print("Food menu is:") 
            print("1.breakfast= bread and jam")  
            print("2. lunch= rajma, rice and butter milk") 
            print("3. dinner= chicken gravy, paneer and roti") 
            n3=int(input("Choose your meal number:"))
            if n3==1:
                print("You have chosen Breakfast") 
                fc=int(input("enter amount of food consumed:")) 
                print("almost 20% of food from breakfast is wasted") 
                print("Amount of food wasted is",0.2*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==2:
                print("You have chosen Lunch") 
                fc=int(input("enter amount of food consumed:"))
                print("almost  30% of luch is wasted") 
                print("Amount of food wasted is",0.3*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==3:
                print("You have chosen Dinner")
                fc=int(input("enter amount of food consumed:"))
                print("almost 40% of dinneer is wasted") 
                print("Amount of food wasted is",0.4*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
        elif n2==4:
            print("You have chosen Thursday") 
            print("Food menu is:") 
            print("1.breakfast= bread and jam")  
            print("2. lunch= rajma, rice and butter milk") 
            print("3. dinner= chicken gravy, paneer and roti") 
            n3=int(input("Choose your meal number:"))
            if n3==1:
                print("You have chosen Breakfast") 
                fc=int(input("enter amount of food consumed:")) 
                print("almost 20% of food from breakfast is wasted") 
                print("Amount of food wasted is",0.2*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==2:
                print("You have chosen Lunch") 
                fc=int(input("enter amount of food consumed:"))
                print("almost  30% of luch is wasted") 
                print("Amount of food wasted is",0.3*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==3:
                print("You have chosen Dinner")
                fc=int(input("enter amount of food consumed:"))
                print("almost 40% of dinneer is wasted") 
                print("Amount of food wasted is",0.4*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
        elif n2==5:
            print("You have chosen Friday") 
            print("Food menu is:") 
            print("1.breakfast= bread and jam")  
            print("2. lunch= rajma, rice and butter milk") 
            print("3. dinner= chicken gravy, paneer and roti") 
            n3=int(input("Choose your meal number:"))
            if n3==1:
                print("You have chosen Breakfast") 
                fc=int(input("enter amount of food consumed:")) 
                print("almost 20% of food from breakfast is wasted") 
                print("Amount of food wasted is",0.2*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==2:
                print("You have chosen Lunch") 
                fc=int(input("enter amount of food consumed:"))
                print("almost  30% of luch is wasted") 
                print("Amount of food wasted is",0.3*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==3:
                print("You have chosen Dinner")
                fc=int(input("enter amount of food consumed:"))
                print("almost 40% of dinneer is wasted") 
                print("Amount of food wasted is",0.4*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
        elif n2==6:
            print("You have chosen Saturday") 
            print("Food menu is:") 
            print("1.breakfast= bread and jam")  
            print("2. lunch= rajma, rice and butter milk") 
            print("3. dinner= chicken gravy, paneer and roti") 
            n3=int(input("Choose your meal number:"))
            if n3==1:
                print("You have chosen Breakfast") 
                fc=int(input("enter amount of food consumed:")) 
                print("almost 20% of food from breakfast is wasted") 
                print("Amount of food wasted is",0.2*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==2:
                print("You have chosen Lunch") 
                fc=int(input("enter amount of food consumed:"))
                print("almost  30% of luch is wasted") 
                print("Amount of food wasted is",0.3*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==3:
                print("You have chosen Dinner")
                fc=int(input("enter amount of food consumed:"))
                print("almost 40% of dinneer is wasted") 
                print("Amount of food wasted is",0.4*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
        elif n2==7:
            print("You have chosen Sunday") 
            print("Food menu is:") 
            print("1.breakfast= bread and jam")  
            print("2. lunch= rajma, rice and butter milk") 
            print("3. dinner= chicken gravy, paneer and roti") 
            n3=int(input("Choose your meal number:"))
            if n3==1:
                print("You have chosen Breakfast") 
                fc=int(input("enter amount of food consumed:")) 
                print("almost 20% of food from breakfast is wasted") 
                print("Amount of food wasted is",0.2*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==2:
                print("You have chosen Lunch") 
                fc=int(input("enter amount of food consumed:"))
                print("almost  30% of luch is wasted") 
                print("Amount of food wasted is",0.3*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==3:
                print("You have chosen Dinner")
                fc=int(input("enter amount of food consumed:"))
                print("almost 40% of dinneer is wasted") 
                print("Amount of food wasted is",0.4*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
    if n1==2:
        print("You have chosen Senbagam")
        print("Select day:") 
        print("1. Monday") 
        print("2. Tuesday") 
        print("3. Wednesday") 
        print("4. Thursday") 
        print("5. Friday") 
        print("6.Saturday") 
        print("7. Sunday") 
        n2=int(input("enter your choice 1,2,3,4,5,6 or 7:"))
        if n2==1:
            print("You have chosen Monday") 
            print("Food menu is:") 
            print("1.breakfast= bread and jam")  
            print("2. lunch= rajma, rice and butter milk") 
            print("3. dinner= chicken gravy, paneer and roti") 
            n3=int(input("Choose your meal number:"))
            if n3==1:
                print("You have chosen Breakfast") 
                fc=int(input("enter amount of food consumed:")) 
                print("almost 20% of food from breakfast is wasted") 
                print("Amount of food wasted is",0.2*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==2:
                print("You have chosen Lunch") 
                fc=int(input("enter amount of food consumed:"))
                print("almost  30% of luch is wasted") 
                print("Amount of food wasted is",0.3*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==3:
                print("You have chosen Dinner")
                fc=int(input("enter amount of food consumed:"))
                print("almost 40% of dinneer is wasted") 
                print("Amount of food wasted is",0.4*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
        elif n2==2:
            print("You have chosen Tuesday") 
            print("Food menu is:") 
            print("1.breakfast= bread and jam")  
            print("2. lunch= rajma, rice and butter milk") 
            print("3. dinner= chicken gravy, paneer and roti") 
            n3=int(input("Choose your meal number:"))
            if n3==1:
                print("You have chosen Breakfast") 
                fc=int(input("enter amount of food consumed:")) 
                print("almost 20% of food from breakfast is wasted") 
                print("Amount of food wasted is",0.2*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==2:
                print("You have chosen Lunch") 
                fc=int(input("enter amount of food consumed:"))
                print("almost  30% of luch is wasted") 
                print("Amount of food wasted is",0.3*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==3:
                print("You have chosen Dinner")
                fc=int(input("enter amount of food consumed:"))
                print("almost 40% of dinneer is wasted") 
                print("Amount of food wasted is",0.4*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
        elif n2==3:
            print("You have chosen Wednesday") 
            print("Food menu is:") 
            print("1.breakfast= bread and jam")  
            print("2. lunch= rajma, rice and butter milk") 
            print("3. dinner= chicken gravy, paneer and roti") 
            n3=int(input("Choose your meal number:"))
            if n3==1:
                print("You have chosen Breakfast") 
                fc=int(input("enter amount of food consumed:")) 
                print("almost 20% of food from breakfast is wasted") 
                print("Amount of food wasted is",0.2*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==2:
                print("You have chosen Lunch") 
                fc=int(input("enter amount of food consumed:"))
                print("almost  30% of luch is wasted") 
                print("Amount of food wasted is",0.3*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==3:
                print("You have chosen Dinner")
                fc=int(input("enter amount of food consumed:"))
                print("almost 40% of dinneer is wasted") 
                print("Amount of food wasted is",0.4*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
        elif n2==4:
            print("You have chosen Thursday") 
            print("Food menu is:") 
            print("1.breakfast= bread and jam")  
            print("2. lunch= rajma, rice and butter milk") 
            print("3. dinner= chicken gravy, paneer and roti") 
            n3=int(input("Choose your meal number:"))
            if n3==1:
                print("You have chosen Breakfast") 
                fc=int(input("enter amount of food consumed:")) 
                print("almost 20% of food from breakfast is wasted") 
                print("Amount of food wasted is",0.2*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==2:
                print("You have chosen Lunch") 
                fc=int(input("enter amount of food consumed:"))
                print("almost  30% of luch is wasted") 
                print("Amount of food wasted is",0.3*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==3:
                print("You have chosen Dinner")
                fc=int(input("enter amount of food consumed:"))
                print("almost 40% of dinneer is wasted") 
                print("Amount of food wasted is",0.4*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
        elif n2==5:
            print("You have chosen Friday") 
            print("Food menu is:") 
            print("1.breakfast= bread and jam")  
            print("2. lunch= rajma, rice and butter milk") 
            print("3. dinner= chicken gravy, paneer and roti") 
            n3=int(input("Choose your meal number:"))
            if n3==1:
                print("You have chosen Breakfast") 
                fc=int(input("enter amount of food consumed:")) 
                print("almost 20% of food from breakfast is wasted") 
                print("Amount of food wasted is",0.2*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==2:
                print("You have chosen Lunch") 
                fc=int(input("enter amount of food consumed:"))
                print("almost  30% of luch is wasted") 
                print("Amount of food wasted is",0.3*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==3:
                print("You have chosen Dinner")
                fc=int(input("enter amount of food consumed:"))
                print("almost 40% of dinneer is wasted") 
                print("Amount of food wasted is",0.4*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
        elif n2==6:
            print("You have chosen Saturday") 
            print("Food menu is:") 
            print("1.breakfast= bread and jam")  
            print("2. lunch= rajma, rice and butter milk") 
            print("3. dinner= chicken gravy, paneer and roti") 
            n3=int(input("Choose your meal number:"))
            if n3==1:
                print("You have chosen Breakfast") 
                fc=int(input("enter amount of food consumed:")) 
                print("almost 20% of food from breakfast is wasted") 
                print("Amount of food wasted is",0.2*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==2:
                print("You have chosen Lunch") 
                fc=int(input("enter amount of food consumed:"))
                print("almost  30% of luch is wasted") 
                print("Amount of food wasted is",0.3*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==3:
                print("You have chosen Dinner")
                fc=int(input("enter amount of food consumed:"))
                print("almost 40% of dinneer is wasted") 
                print("Amount of food wasted is",0.4*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
        elif n2==7:
            print("You have chosen Sunday") 
            print("Food menu is:") 
            print("1.breakfast= bread and jam")  
            print("2. lunch= rajma, rice and butter milk") 
            print("3. dinner= chicken gravy, paneer and roti") 
            n3=int(input("Choose your meal number:"))
            if n3==1:
                print("You have chosen Breakfast") 
                fc=int(input("enter amount of food consumed:")) 
                print("almost 20% of food from breakfast is wasted") 
                print("Amount of food wasted is",0.2*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==2:
                print("You have chosen Lunch") 
                fc=int(input("enter amount of food consumed:"))
                print("almost  30% of luch is wasted") 
                print("Amount of food wasted is",0.3*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==3:
                print("You have chosen Dinner")
                fc=int(input("enter amount of food consumed:"))
                print("almost 40% of dinneer is wasted") 
                print("Amount of food wasted is",0.4*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
    if n1==3:
        print("You have chosen ESQ Block")
        print("Select day:") 
        print("1. Monday") 
        print("2. Tuesday") 
        print("3. Wednesday") 
        print("4. Thursday") 
        print("5. Friday") 
        print("6.Saturday") 
        print("7. Sunday") 
        n2=int(input("enter your choice 1,2,3,4,5,6 or 7:"))
        if n2==1:
            print("You have chosen Monday") 
            print("Food menu is:") 
            print("1.breakfast= bread and jam")  
            print("2. lunch= rajma, rice and butter milk") 
            print("3. dinner= chicken gravy, paneer and roti") 
            n3=int(input("Choose your meal number:"))
            if n3==1:
                print("You have chosen Breakfast") 
                fc=int(input("enter amount of food consumed:")) 
                print("almost 20% of food from breakfast is wasted") 
                print("Amount of food wasted is",0.2*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==2:
                print("You have chosen Lunch") 
                fc=int(input("enter amount of food consumed:"))
                print("almost  30% of luch is wasted") 
                print("Amount of food wasted is",0.3*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==3:
                print("You have chosen Dinner")
                fc=int(input("enter amount of food consumed:"))
                print("almost 40% of dinneer is wasted") 
                print("Amount of food wasted is",0.4*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
        elif n2==2:
            print("You have chosen Tuesday") 
            print("Food menu is:") 
            print("1.breakfast= bread and jam")  
            print("2. lunch= rajma, rice and butter milk") 
            print("3. dinner= chicken gravy, paneer and roti") 
            n3=int(input("Choose your meal number:"))
            if n3==1:
                print("You have chosen Breakfast") 
                fc=int(input("enter amount of food consumed:")) 
                print("almost 20% of food from breakfast is wasted") 
                print("Amount of food wasted is",0.2*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==2:
                print("You have chosen Lunch") 
                fc=int(input("enter amount of food consumed:"))
                print("almost  30% of luch is wasted") 
                print("Amount of food wasted is",0.3*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==3:
                print("You have chosen Dinner")
                fc=int(input("enter amount of food consumed:"))
                print("almost 40% of dinneer is wasted") 
                print("Amount of food wasted is",0.4*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
        elif n2==3:
            print("You have chosen Wednesday") 
            print("Food menu is:") 
            print("1.breakfast= bread and jam")  
            print("2. lunch= rajma, rice and butter milk") 
            print("3. dinner= chicken gravy, paneer and roti") 
            n3=int(input("Choose your meal number:"))
            if n3==1:
                print("You have chosen Breakfast") 
                fc=int(input("enter amount of food consumed:")) 
                print("almost 20% of food from breakfast is wasted") 
                print("Amount of food wasted is",0.2*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==2:
                print("You have chosen Lunch") 
                fc=int(input("enter amount of food consumed:"))
                print("almost  30% of luch is wasted") 
                print("Amount of food wasted is",0.3*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==3:
                print("You have chosen Dinner")
                fc=int(input("enter amount of food consumed:"))
                print("almost 40% of dinneer is wasted") 
                print("Amount of food wasted is",0.4*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
        elif n2==4:
            print("You have chosen Thursday") 
            print("Food menu is:") 
            print("1.breakfast= bread and jam")  
            print("2. lunch= rajma, rice and butter milk") 
            print("3. dinner= chicken gravy, paneer and roti") 
            n3=int(input("Choose your meal number:"))
            if n3==1:
                print("You have chosen Breakfast") 
                fc=int(input("enter amount of food consumed:")) 
                print("almost 20% of food from breakfast is wasted") 
                print("Amount of food wasted is",0.2*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==2:
                print("You have chosen Lunch") 
                fc=int(input("enter amount of food consumed:"))
                print("almost  30% of luch is wasted") 
                print("Amount of food wasted is",0.3*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==3:
                print("You have chosen Dinner")
                fc=int(input("enter amount of food consumed:"))
                print("almost 40% of dinneer is wasted") 
                print("Amount of food wasted is",0.4*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
        elif n2==5:
            print("You have chosen Friday") 
            print("Food menu is:") 
            print("1.breakfast= bread and jam")  
            print("2. lunch= rajma, rice and butter milk") 
            print("3. dinner= chicken gravy, paneer and roti") 
            n3=int(input("Choose your meal number:"))
            if n3==1:
                print("You have chosen Breakfast") 
                fc=int(input("enter amount of food consumed:")) 
                print("almost 20% of food from breakfast is wasted") 
                print("Amount of food wasted is",0.2*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==2:
                print("You have chosen Lunch") 
                fc=int(input("enter amount of food consumed:"))
                print("almost  30% of luch is wasted") 
                print("Amount of food wasted is",0.3*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==3:
                print("You have chosen Dinner")
                fc=int(input("enter amount of food consumed:"))
                print("almost 40% of dinneer is wasted") 
                print("Amount of food wasted is",0.4*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
        elif n2==6:
            print("You have chosen Saturday") 
            print("Food menu is:") 
            print("1.breakfast= bread and jam")  
            print("2. lunch= rajma, rice and butter milk") 
            print("3. dinner= chicken gravy, paneer and roti") 
            n3=int(input("Choose your meal number:"))
            if n3==1:
                print("You have chosen Breakfast") 
                fc=int(input("enter amount of food consumed:")) 
                print("almost 20% of food from breakfast is wasted") 
                print("Amount of food wasted is",0.2*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==2:
                print("You have chosen Lunch") 
                fc=int(input("enter amount of food consumed:"))
                print("almost  30% of luch is wasted") 
                print("Amount of food wasted is",0.3*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==3:
                print("You have chosen Dinner")
                fc=int(input("enter amount of food consumed:"))
                print("almost 40% of dinneer is wasted") 
                print("Amount of food wasted is",0.4*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
        elif n2==7:
            print("You have chosen Sunday") 
            print("Food menu is:") 
            print("1.breakfast= bread and jam")  
            print("2. lunch= rajma, rice and butter milk") 
            print("3. dinner= chicken gravy, paneer and roti") 
            n3=int(input("Choose your meal number:"))
            if n3==1:
                print("You have chosen Breakfast") 
                fc=int(input("enter amount of food consumed:")) 
                print("almost 20% of food from breakfast is wasted") 
                print("Amount of food wasted is",0.2*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==2:
                print("You have chosen Lunch") 
                fc=int(input("enter amount of food consumed:"))
                print("almost  30% of luch is wasted") 
                print("Amount of food wasted is",0.3*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==3:
                print("You have chosen Dinner")
                fc=int(input("enter amount of food consumed:"))
                print("almost 40% of dinneer is wasted") 
                print("Amount of food wasted is",0.4*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
    if n1==4:
        print("You have chosen Meenakshi")
        print("Select day:") 
        print("1. Monday") 
        print("2. Tuesday") 
        print("3. Wednesday") 
        print("4. Thursday") 
        print("5. Friday") 
        print("6.Saturday") 
        print("7. Sunday") 
        n2=int(input("enter your choice 1,2,3,4,5,6 or 7:"))
        if n2==1:
            print("You have chosen Monday") 
            print("Food menu is:") 
            print("1.breakfast= bread and jam")  
            print("2. lunch= rajma, rice and butter milk") 
            print("3. dinner= chicken gravy, paneer and roti") 
            n3=int(input("Choose your meal number:"))
            if n3==1:
                print("You have chosen Breakfast") 
                fc=int(input("enter amount of food consumed:")) 
                print("almost 20% of food from breakfast is wasted") 
                print("Amount of food wasted is",0.2*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==2:
                print("You have chosen Lunch") 
                fc=int(input("enter amount of food consumed:"))
                print("almost  30% of luch is wasted") 
                print("Amount of food wasted is",0.3*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==3:
                print("You have chosen Dinner")
                fc=int(input("enter amount of food consumed:"))
                print("almost 40% of dinneer is wasted") 
                print("Amount of food wasted is",0.4*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
        elif n2==2:
            print("You have chosen Tuesday") 
            print("Food menu is:") 
            print("1.breakfast= bread and jam")  
            print("2. lunch= rajma, rice and butter milk") 
            print("3. dinner= chicken gravy, paneer and roti") 
            n3=int(input("Choose your meal number:"))
            if n3==1:
                print("You have chosen Breakfast") 
                fc=int(input("enter amount of food consumed:")) 
                print("almost 20% of food from breakfast is wasted") 
                print("Amount of food wasted is",0.2*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==2:
                print("You have chosen Lunch") 
                fc=int(input("enter amount of food consumed:"))
                print("almost  30% of luch is wasted") 
                print("Amount of food wasted is",0.3*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==3:
                print("You have chosen Dinner")
                fc=int(input("enter amount of food consumed:"))
                print("almost 40% of dinneer is wasted") 
                print("Amount of food wasted is",0.4*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
        elif n2==3:
            print("You have chosen Wednesday") 
            print("Food menu is:") 
            print("1.breakfast= bread and jam")  
            print("2. lunch= rajma, rice and butter milk") 
            print("3. dinner= chicken gravy, paneer and roti") 
            n3=int(input("Choose your meal number:"))
            if n3==1:
                print("You have chosen Breakfast") 
                fc=int(input("enter amount of food consumed:")) 
                print("almost 20% of food from breakfast is wasted") 
                print("Amount of food wasted is",0.2*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==2:
                print("You have chosen Lunch") 
                fc=int(input("enter amount of food consumed:"))
                print("almost  30% of luch is wasted") 
                print("Amount of food wasted is",0.3*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==3:
                print("You have chosen Dinner")
                fc=int(input("enter amount of food consumed:"))
                print("almost 40% of dinneer is wasted") 
                print("Amount of food wasted is",0.4*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
        elif n2==4:
            print("You have chosen Thursday") 
            print("Food menu is:") 
            print("1.breakfast= bread and jam")  
            print("2. lunch= rajma, rice and butter milk") 
            print("3. dinner= chicken gravy, paneer and roti") 
            n3=int(input("Choose your meal number:"))
            if n3==1:
                print("You have chosen Breakfast") 
                fc=int(input("enter amount of food consumed:")) 
                print("almost 20% of food from breakfast is wasted") 
                print("Amount of food wasted is",0.2*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==2:
                print("You have chosen Lunch") 
                fc=int(input("enter amount of food consumed:"))
                print("almost  30% of luch is wasted") 
                print("Amount of food wasted is",0.3*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==3:
                print("You have chosen Dinner")
                fc=int(input("enter amount of food consumed:"))
                print("almost 40% of dinneer is wasted") 
                print("Amount of food wasted is",0.4*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
        elif n2==5:
            print("You have chosen Friday") 
            print("Food menu is:") 
            print("1.breakfast= bread and jam")  
            print("2. lunch= rajma, rice and butter milk") 
            print("3. dinner= chicken gravy, paneer and roti") 
            n3=int(input("Choose your meal number:"))
            if n3==1:
                print("You have chosen Breakfast") 
                fc=int(input("enter amount of food consumed:")) 
                print("almost 20% of food from breakfast is wasted") 
                print("Amount of food wasted is",0.2*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==2:
                print("You have chosen Lunch") 
                fc=int(input("enter amount of food consumed:"))
                print("almost  30% of luch is wasted") 
                print("Amount of food wasted is",0.3*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==3:
                print("You have chosen Dinner")
                fc=int(input("enter amount of food consumed:"))
                print("almost 40% of dinneer is wasted") 
                print("Amount of food wasted is",0.4*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
        elif n2==6:
            print("You have chosen Saturday") 
            print("Food menu is:") 
            print("1.breakfast= bread and jam")  
            print("2. lunch= rajma, rice and butter milk") 
            print("3. dinner= chicken gravy, paneer and roti") 
            n3=int(input("Choose your meal number:"))
            if n3==1:
                print("You have chosen Breakfast") 
                fc=int(input("enter amount of food consumed:")) 
                print("almost 20% of food from breakfast is wasted") 
                print("Amount of food wasted is",0.2*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==2:
                print("You have chosen Lunch") 
                fc=int(input("enter amount of food consumed:"))
                print("almost  30% of luch is wasted") 
                print("Amount of food wasted is",0.3*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==3:
                print("You have chosen Dinner")
                fc=int(input("enter amount of food consumed:"))
                print("almost 40% of dinneer is wasted") 
                print("Amount of food wasted is",0.4*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
        elif n2==7:
            print("You have chosen Sunday") 
            print("Food menu is:") 
            print("1.breakfast= bread and jam")  
            print("2. lunch= rajma, rice and butter milk") 
            print("3. dinner= chicken gravy, paneer and roti") 
            n3=int(input("Choose your meal number:"))
            if n3==1:
                print("You have chosen Breakfast") 
                fc=int(input("enter amount of food consumed:")) 
                print("almost 20% of food from breakfast is wasted") 
                print("Amount of food wasted is",0.2*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==2:
                print("You have chosen Lunch") 
                fc=int(input("enter amount of food consumed:"))
                print("almost  30% of luch is wasted") 
                print("Amount of food wasted is",0.3*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 
            elif n3==3:
                print("You have chosen Dinner")
                fc=int(input("enter amount of food consumed:"))
                print("almost 40% of dinneer is wasted") 
                print("Amount of food wasted is",0.4*fc) 
                print("Please save food") 
                n=input("want to continue:yes or no") 

